#!/usr/bin/env bash
#
# Post-deploy smoke test. Exercises the live container over HTTP: readiness,
# auth, a real inference, and the batch partial-failure contract.
#
#   ./scripts/smoke-test.sh [BASE_URL] [IMAGE_TAG]
#
# API_KEY is read from the environment, or from .env.prod if present.
set -euo pipefail

BASE_URL="${1:-http://127.0.0.1:3000}"
IMAGE="${2:-image-moderation:latest}"

if [[ -z "${API_KEY:-}" ]]; then
  for f in .env.prod .env.staging .env; do
    if [[ -f "$f" ]]; then
      # Take the first key from the comma-separated list.
      API_KEY="$(grep -E '^API_KEYS=' "$f" | head -1 | cut -d= -f2- | cut -d, -f1 | tr -d '"'"'"' ')"
      [[ -n "$API_KEY" ]] && { echo "using API key from $f"; break; }
    fi
  done
fi
if [[ -z "${API_KEY:-}" ]]; then
  echo "FAIL: set API_KEY, or provide a .env.prod with API_KEYS=" >&2
  exit 1
fi

pass=0; fail=0
check() { # check <name> <expected-status> <actual-status> [extra]
  if [[ "$2" == "$3" ]]; then
    printf '  ok   %-42s %s\n' "$1" "$3"; pass=$((pass+1))
  else
    printf '  FAIL %-42s expected %s, got %s %s\n' "$1" "$2" "$3" "${4:-}"; fail=$((fail+1))
  fi
}
status() { curl -s -o /tmp/smoke.$$ -w '%{http_code}' "$@"; }
body() { cat /tmp/smoke.$$; }

echo "target: $BASE_URL"

# --- readiness ------------------------------------------------------------
echo "waiting for /ready (model load can take up to 60s)..."
ready=false
for i in $(seq 1 60); do
  if curl -fsS "$BASE_URL/ready" >/dev/null 2>&1; then
    echo "  ready after ${i}s"; ready=true; break
  fi
  sleep 1
done
[[ "$ready" == true ]] || { echo "FAIL: /ready never returned 200"; exit 1; }

check "GET /health"  200 "$(status "$BASE_URL/health")"
check "GET /ready"   200 "$(status "$BASE_URL/ready")"
check "GET /metrics" 200 "$(status "$BASE_URL/metrics")"

# --- a test image, generated by the image's own sharp (nothing downloaded) --
# SMOKE_IMAGE_B64 lets this run against a host that has no local copy of the
# image (or no docker at all), e.g. when testing through nginx from elsewhere.
if [[ -n "${SMOKE_IMAGE_B64:-}" ]]; then
  echo "using the test image supplied in SMOKE_IMAGE_B64"
  B64="$SMOKE_IMAGE_B64"
else
echo "generating a test image with the container's sharp..."
B64="$(docker run --rm --entrypoint node "$IMAGE" -e '
  const sharp = require("sharp");
  sharp({ create: { width: 400, height: 300, channels: 3, background: { r: 180, g: 90, b: 70 } } })
    .jpeg({ quality: 90 }).toBuffer()
    .then((b) => process.stdout.write(b.toString("base64")));
')"
fi
[[ -n "$B64" ]] || { echo "FAIL: could not generate a test image"; exit 1; }
echo "  ${#B64} base64 chars"

# --- auth ------------------------------------------------------------------
check "POST /v1/moderate without key" 401 \
  "$(status -X POST "$BASE_URL/v1/moderate" -H 'content-type: application/json' -d "{\"base64\":\"$B64\"}")"

check "POST /v1/moderate with bad key" 401 \
  "$(status -X POST "$BASE_URL/v1/moderate" -H 'X-API-Key: not-a-real-key-at-all' \
      -H 'content-type: application/json' -d "{\"base64\":\"$B64\"}")"

# --- a real inference ------------------------------------------------------
code="$(status -X POST "$BASE_URL/v1/moderate" -H "X-API-Key: $API_KEY" \
  -H 'content-type: application/json' -d "{\"base64\":\"$B64\"}")"
check "POST /v1/moderate (valid)" 200 "$code" "$(body | head -c 120)"
if [[ "$code" == 200 ]]; then
  body > /tmp/smoke-result.$$
  python3 - "/tmp/smoke-result.$$" <<'PY' || fail=$((fail+1))
import json, sys
d = json.load(open(sys.argv[1]))
assert d["success"] is True, d
data, meta = d["data"], d["meta"]
assert data["verdict"] in ("allow", "review", "block"), data
assert sorted(data["scores"]) == ["drawing", "hentai", "neutral", "porn", "sexy"], data
assert len(data["image"]["hash"]) == 64, data
assert data["image"]["width"] == 400 and data["image"]["height"] == 300, data
assert meta["modelVersion"] == "nsfwjs-mobilenet-v2", meta
print(f"  ok   verdict={data['verdict']} top={data['topClass']} "
      f"nsfwScore={data['nsfwScore']:.4f} {meta['processingMs']:.1f}ms")
PY
  rm -f /tmp/smoke-result.$$
fi

# --- rejections ------------------------------------------------------------
check "non-image payload -> 415" 415 \
  "$(status -X POST "$BASE_URL/v1/moderate" -H "X-API-Key: $API_KEY" \
      -H 'content-type: application/json' -d '{"base64":"bm90YW5pbWFnZWF0YWxs"}')"

check "url to host network -> 422" 422 \
  "$(status -X POST "$BASE_URL/v1/moderate" -H "X-API-Key: $API_KEY" \
      -H 'content-type: application/json' -d '{"url":"http://169.254.169.254/latest/meta-data/"}')"

# --- batch: valid request stays 200 even when items fail -------------------
code="$(status -X POST "$BASE_URL/v1/moderate/batch" -H "X-API-Key: $API_KEY" \
  -H 'content-type: application/json' \
  -d "{\"images\":[{\"id\":\"ok\",\"base64\":\"$B64\"},{\"id\":\"bad\",\"base64\":\"bm90YW5pbWFnZQ==\"}]}")"
check "POST /v1/moderate/batch (1 ok, 1 bad)" 200 "$code"
if [[ "$code" == 200 ]]; then
  body > /tmp/smoke-batch.$$
  python3 - "/tmp/smoke-batch.$$" <<'PY' || fail=$((fail+1))
import json, sys
d = json.load(open(sys.argv[1]))
s = d["data"]["summary"]
assert d["success"] is True and s == {"total": 2, "succeeded": 1, "failed": 2 - 1}, d
r = d["data"]["results"]
assert r[0]["success"] is True and r[1]["success"] is False, r
assert r[1]["error"]["code"] == "UNSUPPORTED_MEDIA_TYPE", r[1]
print(f"  ok   batch summary={s} item1={r[1]['error']['code']}")
PY
  rm -f /tmp/smoke-batch.$$
fi

rm -f /tmp/smoke.$$
echo
echo "passed: $pass   failed: $fail"
[[ "$fail" -eq 0 ]] || exit 1
echo "SMOKE TEST OK"
